# Generated by Django 5.2.10 on 2026-01-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitwiselink',
            name='api_key',
        ),
        migrations.AddField(
            model_name='splitwiselink',
            name='oauth_token',
            field=models.CharField(default='default', help_text='OAuth Access Token', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splitwiselink',
            name='oauth_token_secret',
            field=models.CharField(default='default', help_text='OAuth Access Token Secret', max_length=255),
            preserve_default=False,
        ),
    ]
